/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nirajmchauhan' at '1/14/17 11:26 AM' with Gradle 3.1
 *
 * @author nirajmchauhan, @date 1/14/17 11:26 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
